# Generated by Django 5.2.7 on 2025-11-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_add_deletion_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('content_text', models.TextField()),
                ('is_deleted', models.BooleanField()),
                ('deletion_type', models.CharField(default='soft', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingest_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'item_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('kind', models.TextField()),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
